In [10]:
import pandas as pd
from sqlalchemy import create_engine
import mysql.connector as sql

In [2]:
#pip install SQLAlchemy

In [11]:
import mysql.connector as sql

con_sql=sql.connect(host="localhost",user="root",password="Anjali@2001",database="hr")
if con_sql.is_connected:
   print("connected")
else:
  print("not connected")

connected

In [14]:
df = pd.read_csv('FootBall_Data_Merged_Cleaned.csv')
df=df.drop(['Unnamed: 0'],axis=1)
df

,appearance_id,game_id,player_id,date,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2224728_119169,2224728.0,119169,2012-07-13 00:00:00,Aron Johannsson,DK1,0.0,0.0,0.0,0.0,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31 00:00:00,CAA Stellar
1,2232104_119169,2232104.0,119169,2012-07-19 00:00:00,Aron Johannsson,ELQ,0.0,0.0,0.0,0.0,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31 00:00:00,CAA Stellar
2,2224568_119169,2224568.0,119169,2012-07-23 00:00:00,Aron Johannsson,DK1,0.0,0.0,0.0,0.0,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31 00:00:00,CAA Stellar
3,2244352_119169,2244352.0,119169,2012-07-26 00:00:00,Aron Johannsson,ELQ,0.0,0.0,0.0,0.0,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31 00:00:00,CAA Stellar
4,2224567_119169,2224567.0,119169,2012-07-29 00:00:00,Aron Johannsson,DK1,0.0,0.0,0.0,0.0,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,400000.0,4000000.0,2024-12-31 00:00:00,CAA Stellar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649,Not Available,2757218.0,605144,Not Available,Not Available,Not Available,0.0,0.0,0.0,0.0,...,United States,2001-07-28,Attacking Midfield,Midfield,both,180.0,2000000.0,6000000.0,2024-12-31 00:00:00,Octagon
4650,Not Available,2757218.0,623872,Not Available,Not Available,Not Available,0.0,0.0,0.0,0.0,...,United States,2003-02-21,Attacking Midfield,Midfield,right,183.0,75000.0,75000.0,Not Available,PRO FC
4651,Not Available,2757218.0,467437,Not Available,Not Available,Not Available,0.0,0.0,0.0,0.0,...,Germany,2002-05-28,Attacking Midfield,Midfield,right,187.0,5000000.0,5000000.0,2024-06-30 00:00:00,ROOF
4652,Not Available,2757218.0,103559,Not Available,Not Available,Not Available,0.0,0.0,0.0,0.0,...,Norway,1990-10-02,Central Midfield,Midfield,right,184.0,400000.0,1400000.0,2024-05-31 00:00:00,Not Available
4653,Not Available,2757218.0,670096,Not Available,Not Available,Not Available,0.0,0.0,0.0,0.0,...,United States,2001-09-24,Central Midfield,Midfield,right,188.0,2000000.0,2500000.0,2025-06-30 00:00:00,PROSPORT Management

In [15]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import pymysql 
import matplotlib.pyplot as plt

hostname = "localhost"
dbname = "hr"
uname = "root"
pwd = "Anjali@2001"
enc_pwd = quote_plus(pwd)

eng= create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}".format(host=hostname,db=dbname,user=uname,pw=enc_pwd))

In [20]:

# Write the DataFrame to a SQL table in the 'hr' MySQL database
# The table will be named 'FootBall_Data_Merged_Cleaned', and if it exists, it will be replaced
#df.to_sql('FootBall_Data_Set', con=eng, if_exists='replace', index=False)

# Verify the DataFrame (optional)
print(df)

       appearance_id    game_id  player_id                 date  \
0     2224728_119169  2224728.0     119169  2012-07-13 00:00:00
1     2232104_119169  2232104.0     119169  2012-07-19 00:00:00
2     2224568_119169  2224568.0     119169  2012-07-23 00:00:00
3     2244352_119169  2244352.0     119169  2012-07-26 00:00:00
4     2224567_119169  2224567.0     119169  2012-07-29 00:00:00
...              ...        ...        ...                  ...
4649   Not Available  2757218.0     605144        Not Available
4650   Not Available  2757218.0     623872        Not Available
4651   Not Available  2757218.0     467437        Not Available
4652   Not Available  2757218.0     103559        Not Available
4653   Not Available  2757218.0     670096        Not Available

        player_name_x competition_id_x  yellow_cards  red_cards  goals  \
0     Aron Johannsson              DK1           0.0        0.0    0.0
1     Aron Johannsson              ELQ           0.0        0.0    0.0
2     Aron Johannsson              DK1           0.0        0.0    0.0
3     Aron Johannsson              ELQ           0.0        0.0    0.0
4     Aron Johannsson              DK1           0.0        0.0    0.0
...               ...              ...           ...        ...    ...
4649    Not Available    Not Available           0.0        0.0    0.0
4650    Not Available    Not Available           0.0        0.0    0.0
4651    Not Available    Not Available           0.0        0.0    0.0
4652    Not Available    Not Available           0.0        0.0    0.0
4653    Not Available    Not Available           0.0        0.0    0.0

      assists  ...  country_of_birth date_of_birth        sub_position  \
0         0.0  ...     United States    1990-11-10      Centre-Forward
1         0.0  ...     United States    1990-11-10      Centre-Forward
2         0.0  ...     United States    1990-11-10      Centre-Forward
3         0.0  ...     United States    1990-11-10      Centre-Forward
4         0.0  ...     United States    1990-11-10      Centre-Forward
...       ...  ...               ...           ...                 ...
4649      0.0  ...     United States    2001-07-28  Attacking Midfield
4650      0.0  ...     United States    2003-02-21  Attacking Midfield
4651      0.0  ...           Germany    2002-05-28  Attacking Midfield
4652      0.0  ...            Norway    1990-10-02    Central Midfield
4653      0.0  ...     United States    2001-09-24    Central Midfield

     position_y   foot  height_in_cm  market_value_in_eur  \
0        Attack  right         184.0             400000.0
1        Attack  right         184.0             400000.0
2        Attack  right         184.0             400000.0
3        Attack  right         184.0             400000.0
4        Attack  right         184.0             400000.0
...         ...    ...           ...                  ...
4649   Midfield   both         180.0            2000000.0
4650   Midfield  right         183.0              75000.0
4651   Midfield  right         187.0            5000000.0
4652   Midfield  right         184.0             400000.0
4653   Midfield  right         188.0            2000000.0

     highest_market_value_in_eur contract_expiration_date           agent_name
0                      4000000.0      2024-12-31 00:00:00          CAA Stellar
1                      4000000.0      2024-12-31 00:00:00          CAA Stellar
2                      4000000.0      2024-12-31 00:00:00          CAA Stellar
3                      4000000.0      2024-12-31 00:00:00          CAA Stellar
4                      4000000.0      2024-12-31 00:00:00          CAA Stellar
...                          ...                      ...                  ...
4649                   6000000.0      2024-12-31 00:00:00              Octagon
4650                     75000.0            Not Available               PRO FC
4651                   5000000.0      2024-06-30 00:00:00                 ROOF
4652                   1400000.0      2024-05-31 00:00:00        Not Available
4653                   2500000.0      2025-06-30 00:00:00  PROSPORT Management

[4654 rows x 53 columns]

C:\Users\srini\AppData\Local\Temp\ipykernel_21300\3735509450.py:3: UserWarning: The provided table name 'FootBall_Data_Set' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql('FootBall_Data_Set', con=eng, if_exists='replace', index=False)